big file structure re-org; docs update; fixing paths and names

diff --git a/examples/98_MPS/run_throughput_test b/examples/98_MPS/run_throughput_test
--- a/examples/98_MPS/run_throughput_test
+++ b/examples/98_MPS/run_throughput_test
@@ -1,3 +1,5 @@
+#!/bin/bash -e
+#
 # Copyright (c) 2018, NVIDIA CORPORATION. All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -23,35 +25,47 @@
 # OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 # OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+#
+cleanup() {
+  kill $(jobs -p) ||:
+  echo quit | nvidia-cuda-mps-control > /dev/null 2>&1 ||:
+}
+trap "cleanup" EXIT SIGINT SIGTERM
 
-INCLUDE(GRPCGenerateCPP)
-PROTOBUF_GENERATE_CPP(PROTO_SRCS PROTO_HDRS protos/simple.proto)
-PROTOBUF_GENERATE_GRPC_CPP(PROTO_GRPC_SRCS PROTO_GRPC_HDRS protos/simple.proto)
+NCTX=${1:-1}
+BS=${2:-1}
+ENG=${3:-/work/models/ResNet-50-b1-int8.engine}
+MPS=${4:-"MPS"}
 
-include_directories(${Protobuf_INCLUDE_DIRS})
-include_directories(${CMAKE_CURRENT_BINARY_DIR})
+if [ ! -e $ENG ]; then
+    echo "$ENG not found"
+    exit 911
+fi
 
+if [ "$MPS" = "MPS" ]; then
+  nvidia-cuda-mps-control -d ||:
+fi
 
-add_library(protos
-    ${PROTO_SRCS}
-    ${PROTO_GRPC_SRCS})
+sleep 1
 
-add_executable(server.x
-    src/server.cpp)
+echo "starting $NCTX inference services"
+for i in $(seq 1 $NCTX);
+do
+  port=$(echo "50050 + $i" | bc)
+  /work/build/examples/02_TensorRT_GRPC/inference-grpc.x --port $port --engine=${ENG} > /dev/null 2>&1 &
+  wait-for-it.sh localhost:$port --timeout=0 -- echo "Server ${i} is ready." > /dev/null 2>&1
+done
 
-target_link_libraries(server.x
-    yais
-    protos
-    ${_GRPC_GRPCPP_UNSECURE}
-    ${_PROTOBUF_LIBPROTOBUF}
-)
+echo "starting load balancer"
+../99_LoadBalancer/run_loadbalancer.py -n $NCTX 
+# envoy -c /tmp/lb-envoy.yaml --disable-hot-restart > /dev/null 2>&1 &
+envoy -c /tmp/lb-envoy.yaml > /dev/null 2>&1 &
+wait-for-it.sh localhost:50050 --timeout=0 -- echo "Load balancer is ready." > /dev/null 2>&1
 
-add_executable(client.x
-    src/client.cpp)
+echo "running test client"
+/work/build/examples/02_TensorRT_GRPC/client-async.x --count=1000 --port=50050
 
-target_link_libraries(client.x
-    yais
-    protos
-    ${_GRPC_GRPCPP_UNSECURE}
-    ${_PROTOBUF_LIBPROTOBUF}
-)
+echo
+echo "Starting a shell keeping the services and load-balancer running..."
+echo "Try /work/build/examples/02_TensorRT_GRPC/siege.x --rate=2000 --port=50050"
+bash --rcfile <(echo "PS1='Throughput Subshell: '")
